apiVersion: v1
kind: Service
metadata:
  name: kubevirt-velero-annotations-remover
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 443
  selector:
    app: kubevirt-velero-annotations-remover
