apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kubevirt-velero-annotations-remover
  annotations:
    cert-manager.io/inject-ca-from: {{ $.Release.Namespace }}/webhook-tls
webhooks:
  - name: kubevirt-velero-annotations-remover.{{ $.Release.Namespace }}.svc
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE", "UPDATE"]
    clientConfig:
      service:
        name: kubevirt-velero-annotations-remover
        namespace: {{ $.Release.Namespace}}
        path: /mutate
      # caBundle is automatically injected by cert-manager
    admissionReviewVersions: ["v1"]
    sideEffects: None
    objectSelector:
      matchLabels:
        kubevirt.io: virt-launcher
